# Test environment
#mongodb_hostname: order-db
#mongodb_database_name: testOrderDB

# Server properties
server:
  port: 8092

# Application properties
spring:
  application:
    name: ORDER-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
